#!/usr/bin/env bash
# self-identity.sh — the PURE half of a seat deriving its own pane (#1152).
#
# "Pure" is the whole point of this file. It holds the mark, the line contract,
# the matcher and the record row, and it holds NOTHING that reaches a terminal:
# no pane candidate, no emit, no pane read, no writer that a caller could hand a
# raw pane to. Those are the parts whose shape still depends on a measurement
# that has not come back (can a codex seat read panes at all?), and on who owns
# the projection writes. Keeping them out is not tidiness -- a function that
# takes a pane id from its caller is an authority bypass, because the caller
# could name any pane at all.
#
# WHAT THE MARK IS FOR. A seat whose commands run outside its pane cannot learn
# which pane is its own from the environment: the environment answers about the
# PROCESS, and for a seat under a shared app-server the process is not where the
# seat lives (measured, #1112: three seats resolving one pane while sitting in
# three). What does distinguish them is where the seat's own output renders. So
# the seat emits a mark and looks for it.
#
# THE MARK IS A SECRET, NOT A RARITY. "Present in one pane" proves nothing on its
# own -- anyone can type the same string, and during the #1124 measurements
# someone did, producing two panes with one hit each and no way to tell them
# apart. The mark here is generated by the seat, for one use, and MUST NOT leave
# the process before the observation is complete. That is what makes a hit
# evidence: not that the string is unusual, but that nobody else could know it.
# Break that and the evidence is gone:
#
#   sending a message that contains the mark before observing  -> transmitted
#   logging the mark where another party can read it           -> transmitted
#   reusing a mark                                             -> an old hit and
#                                                                 a new one are
#                                                                 indistinguishable
#
# ONE USE, NEVER TRANSMITTED BEFORE THE MATCH. Stated here because it cannot be
# enforced from inside these functions -- it is a property of the caller, and the
# suite pins it separately.

[ -n "${_AGMSG_SELF_IDENTITY_SH:-}" ] && return 0
_AGMSG_SELF_IDENTITY_SH=1

# The fixed prefix. It exists so a line can be recognised as a mark line at all,
# and so a matcher never has to guess whether a bare token was ours.
_AGMSG_SELF_MARK_PREFIX="agmsg-self-"

# Total mark length, prefix included. 17 = prefix(11) + 6 is NOT what this is:
# the digest part carries the entropy and is sized for it, and the prefix is
# added on top. The length is fixed rather than trimmed to fit a pane, because a
# mark that is shortened to survive wrapping is a mark with less entropy, and
# entropy is the only thing standing between "my output" and "someone typed it".
# A mark that wraps simply is not observed -- which is a `not_observed`, not a
# reason to shorten it.
_AGMSG_SELF_MARK_DIGEST_CHARS=13

# A fresh mark. Local, one use, and never derived from anything a caller passes
# in -- a caller-supplied seed would let the caller predict (or replay) the mark,
# which is the same hole as transmitting it.
agmsg_self_mark() {
  local raw hex
  # Three independent sources so a weak one cannot flatten the result: the
  # kernel's entropy where it exists, this process's identity, and the clock.
  raw="$( { head -c 32 /dev/urandom 2>/dev/null | od -An -tx1 2>/dev/null; \
            printf '%s %s' "$$" "$(date -u +%s 2>/dev/null)"; } | tr -d ' \n' )"
  [ -n "$raw" ] || return 1
  command -v agmsg_sha256 >/dev/null 2>&1 || return 1
  hex="$(printf '%s' "$raw" | agmsg_sha256)" || return 1
  [ -n "$hex" ] || return 1
  # base32 over the hex, lower-cased, so the line survives terminals that fold
  # case and readers that split on punctuation. Only [a-z2-7] appear.
  printf '%s%s\n' "$_AGMSG_SELF_MARK_PREFIX" \
    "$(printf '%s' "$hex" | _agmsg_self_base32 | cut -c1-"$_AGMSG_SELF_MARK_DIGEST_CHARS")"
}

# base32 (RFC 4648 alphabet, lower case, no padding) of the hex string on stdin.
# Written here rather than shelling out because `base32` is not on the minimal
# PATH the entry points are required to work under.
_agmsg_self_base32() {
  LC_ALL=C awk '
    BEGIN { a = "abcdefghijklmnopqrstuvwxyz234567" }
    {
      n = length($0); bits = ""; out = ""
      for (i = 1; i <= n; i++) {
        c = tolower(substr($0, i, 1))
        v = index("0123456789abcdef", c) - 1
        if (v < 0) continue
        for (b = 8; b >= 1; b /= 2) { bits = bits ((int(v / b) % 2) ? "1" : "0") }
      }
      for (i = 1; i + 4 <= length(bits); i += 5) {
        v = 0
        for (j = 0; j < 5; j++) { v = v * 2 + substr(bits, i + j, 1) }
        out = out substr(a, v + 1, 1)
      }
      print out
    }'
}

# The line a seat emits, and the only line a matcher accepts. One line, nothing
# before or after it on that line: a mark with anything else on the row cannot be
# matched exactly, and an exact match is the whole contract.
agmsg_self_mark_line() {   # <mark>
  [ -n "${1:-}" ] || return 1
  printf '%s\n' "$1"
}

# Does this line, as read back from a pane, carry exactly this mark?
#
# Only a trailing CR is normalised away -- terminals differ on line endings and
# nothing else about the row may be adjusted. Trimming spaces, or matching a
# substring, would accept a row that merely CONTAINS the mark, and a row that
# contains it is exactly what someone quoting it produces.
_agmsg_self_line_is_mark() {   # <line> <mark>
  local line="${1-}" mark="${2-}"
  [ -n "$mark" ] || return 1
  line="${line%$'\r'}"
  [ "$line" = "$mark" ]
}

# The classifier. PURE, and deliberately not a chooser.
#
# It takes an observation that SOMEONE ELSE made, in a file, and says which of
# four things that observation is. It does not acquire a candidate, does not read
# a pane, and does not select a location -- those belong to the half whose shape
# is still waiting on a measurement, and a pure function that quietly did them
# would be that half wearing a different name.
#
# Input file, one record per line:
#
#   <terminal>\t<pane>\t<line>     a line that was read from that pane
#   !\t<terminal>\t<pane>          that pane could NOT be read
#
# Output:
#
#   rc 0   unique\t<terminal>\t<pane>   exactly one pane carried the mark, and
#                                       every pane in the observation was read
#   rc 1   not_observed                 no pane carried it
#   rc 1   ambiguous                    more than one pane carried it
#   rc 1   unreadable                   at least one pane could not be read
#
# The `unique` row carries the pane as a WITNESS -- the thing the observation
# showed -- not as a decision. Whoever asked is the one entitled to act on it.
#
# UNREADABLE BEATS A HIT, deliberately. One hit plus one pane nobody could read
# is not "exactly one": it is "one that we saw", and the mark could be in the
# pane that would not open. Uniqueness is a claim about ALL panes, so a gap in
# the observation is a gap in the claim. Answering `not_observed` there, or
# answering with the hit, is the fold this codebase keeps paying for -- treating
# "could not read" as "not there".
agmsg_self_classify() {   # <mark> <observation-file>
  local mark="${1:-}" obs="${2:-}" line term pane text hits="" n=0 unreadable=0
  [ -n "$mark" ] || { printf 'unreadable\n'; return 1; }
  # A file that cannot be read is not an empty observation. Saying
  # `not_observed` for it would report "the mark is nowhere" on the strength of
  # never having looked.
  [ -n "$obs" ] && [ -r "$obs" ] || { printf 'unreadable\n'; return 1; }
  while IFS= read -r line || [ -n "$line" ]; do
    [ -n "$line" ] || continue
    case "$line" in
      '!'$'\t'*) unreadable=1; continue ;;
    esac
    term="${line%%$'\t'*}"; line="${line#*$'\t'}"
    pane="${line%%$'\t'*}"; text="${line#*$'\t'}"
    [ -n "$term" ] && [ -n "$pane" ] || continue
    _agmsg_self_line_is_mark "$text" "$mark" || continue
    # One pane may carry the mark on several rows; that is one pane, not two.
    case "$hits" in
      *"$term:$pane;"*) continue ;;
    esac
    hits="$hits$term:$pane;"
    n=$((n + 1))
  done < "$obs"
  if [ "$unreadable" = 1 ]; then
    printf 'unreadable\n'; return 1
  fi
  case "$n" in
    0) printf 'not_observed\n'; return 1 ;;
    1) : ;;
    *) printf 'ambiguous\n';    return 1 ;;
  esac
  hits="${hits%;}"
  printf 'unique\t%s\t%s\n' "${hits%%:*}" "${hits#*:}"
}
